// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
    public partial class CollectionCellViewController : UICollectionViewCell
    {
        #region Cell Identifier
        public static readonly NSString Key = new NSString(nameof(CollectionCellViewController));
        #endregion

        bool isEditEnabled = false;

        #region Properties
        public string Id
        {
            get;
            set;
        }
        public string Name
        {
            get => lblName.Text;
            set => lblName.Text = value;
        }
        public string Position
        {
            get => lblPosition.Text;
            set => lblPosition.Text = value;
        }

        public string Status
        {
            get => lblStatus.Text;
            set {
                if (value == "Online")
                    lblStatus.TextColor = UIColor.Green;

                else
                    lblStatus.TextColor = UIColor.Red;
                lblStatus.Text = value;
            }
        }
        public UIButton BtnEdit
        {
            get => btnEdit;
            set => BtnEdit = value;
        }
        public UIButton BtnDelete
        {
            get => btnDelete;
            // set => null;
        }
        public UIButton BtnGoOnline
        {
            get => btnGoOnline;
            // set => null;
        }

        #endregion
        partial void btnEnableEdit_TouchUpInside(NSObject sender)
        {
            if (isEditEnabled)
            {
                btnEdit.Hidden = true;
                btnDelete.Hidden = true;
                btnGoOnline.Hidden = true;
                isEditEnabled = false;
            }
            else
            {
                btnEdit.Hidden = false;
                btnDelete.Hidden = false;
                btnGoOnline.Hidden = false;
                isEditEnabled = true;
            }
        }

        public CollectionCellViewController (IntPtr handle) : base (handle)
		{
            
		}

        void BtnEdit_TouchUpInside(object sender, EventArgs e)
        {
            var s = "Hi";
        }

	}
}
