// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
	public partial class WorkerTableCellViewController : UITableViewCell
	{
        public static readonly NSString key = new NSString(nameof(WorkerTableCellViewController));
		public WorkerTableCellViewController (IntPtr handle) : base (handle)
		{
		}
        public string LblHours { get => lblHours.Text; set => lblHours.Text = value; }
        public string LblAmount { get => lblAmount.Text; set => lblAmount.Text = value; }
        public UIButton BtnDetails { get => btnDetails; set => btnDetails = value; }
	}
}
