// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
	public partial class WorkerMainMenuTableCellViewController : UITableViewCell
	{
		public WorkerMainMenuTableCellViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
