// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
    public partial class CollectionCellViewController : UICollectionViewCell
    {
        #region Cell Identifier
        public static readonly NSString Key = new NSString(nameof(CollectionCellViewController));
        #endregion

        #region Properties

        public string Name
        {
            get => lblName.Text;
            set => lblName.Text = value;
        }

        #endregion

        public CollectionCellViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
