// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
    public partial class MainMenuViewController : UIViewController,IUICollectionViewDataSource, IUICollectionViewDelegate,IUICollectionViewDelegateFlowLayout
	{
		public MainMenuViewController (IntPtr handle) : base (handle)
		{
            
		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            CollectionView.Delegate = this;
            CollectionView.DataSource = this;
        }

        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var cell = collectionView.DequeueReusableCell(CollectionCellViewController.Key, indexPath) as CollectionCellViewController;
            cell.Name = "Sebastian";
            cell.BackgroundColor = UIColor.LightGray;
            return cell;
        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            return 4;
        }
	}
}
