// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Firebase.Database;

namespace TimeTracking
{
	public partial class AddUserViewController : UIViewController
	{
        DatabaseReference root = Database.DefaultInstance.GetRootReference();
        DatabaseReference userNode;
        DatabaseReference rfidNode;
		public AddUserViewController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            userNode = root.GetChild("team_members");
            rfidNode = root.GetChild("rfid");
 
        }
        partial void AddUser_TouchUpInside(NSObject sender)
        {
            DatabaseReference adduserNode = userNode.GetChildByAutoId();
            double fare = Double.Parse(lblAmount.Text);
            string position = lblPosition.Text;
            string name = lblName.Text;
            string rfid = lblRfid.Text;
            if (fare <= 0 || fare.ToString() == null || fare.ToString().Length <= 0 || position.Length <= 0 || position == null || name == null || name.Length <= 0)
            {
                //TODO: Add warning to user;
            }
            else
            {
                DatabaseReference addrfidNode = rfidNode.GetChildByAutoId();
                object[] rfid_keys = { "id", "status", "tag" };
                object[] rfid_val = { addrfidNode.Key, 0, lblRfid.Text };
                var rfid_data = NSDictionary.FromObjectsAndKeys(rfid_val, rfid_keys, rfid_keys.Length);
                addrfidNode.SetValue(rfid_data);
                object[] keys = { "authid", "fare", "id", "name", "position", "rfid" };
                object[] values = { "undefined", fare, adduserNode.Key, name, position, addrfidNode.Key };
                var data = NSDictionary.FromObjectsAndKeys(values, keys, keys.Length);
                adduserNode.SetValue(data);
                this.NavigationController.PopViewController(true);
            }

        }
    }
}
