// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
	public partial class AddUserViewController : UIViewController
	{
		public AddUserViewController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
  
          //  txtLechuga.Text = Chicken;



        }
	}
}
