// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
    public partial class CollectionCellViewController : UICollectionViewCell
    {
        #region Cell Identifier
        public static readonly NSString Key = new NSString(nameof(CollectionCellViewController));
        #endregion

        #region Properties

        public string Name
        {
            get => lblName.Text;
            set => lblName.Text = value;
        }
        public string Position
        {
            get => lblPosition.Text;
            set => lblPosition.Text = value;
        }

        public string Status
        {
            get => lblStatus.Text;
            set {
                if (value == "Online")
                    lblStatus.TextColor = UIColor.Green;

                else
                    lblStatus.TextColor = UIColor.Red;
                lblStatus.Text = value;
            }
        }

        #endregion

        public CollectionCellViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
