// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
	public partial class EditUserViewController : UIViewController
	{
		public EditUserViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
