// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TimeTracking
{
    public partial class EditUserViewController : UIViewController
    {
        public EditUserViewController(IntPtr handle) : base(handle)
        {
        }
        public string Id
        {
            get;
            set;
        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitializeComponents();

        }
        #region Internal Functionality
        void InitializeComponents()
        {
            var user_id = Id; 
            UITapGestureRecognizer lblPositionTap = new UITapGestureRecognizer(() => {
                
            });
            LblPosition.UserInteractionEnabled = true;
            LblPosition.AddGestureRecognizer(lblPositionTap);
        }

        #endregion
    }
}
