// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace TimeTracking
{
	public partial class WorkerMainMenuTableViewController : UITableViewController
	{
        Employee employee_details;
        public Employee Employee { get; set; }
        public WorkerMainMenuTableViewController (IntPtr handle) : base (handle) {}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            employee_details = Employee;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath){
            var cell = tableView.DequeueReusableCell(WorkerMainMenuTableCellViewController.key, indexPath) as WorkerMainMenuTableCellViewController;
            if (employee_details != null)
            {
                cell.LblStart = employee_details.WorkedTime[indexPath.Row].Start_Date.ToString();
                cell.LblEnd = employee_details.WorkedTime[indexPath.Row].End_Date.ToString();
                TimeSpan worked_time = employee_details.WorkedTime[indexPath.Row].End_Date - employee_details.WorkedTime[indexPath.Row].Start_Date;
                cell.LblTime = worked_time.ToString();
            }
            return cell;

        }
        public override nint RowsInSection(UITableView tableView, nint section) => employee_details != null ? employee_details.WorkedTime.Count : 1;
        [Export("numberOfSectionsInTableView:")]
        public override nint NumberOfSections(UITableView tableView) => 1;
        [Export("tableView:titleForHeaderInSection:")]
        public override string TitleForHeader(UITableView tableView, nint section) => employee_details != null ? employee_details.Name : "No Name";

        public override void PrepareForSegue(UIStoryboardSegue segue, Foundation.NSObject sender)
        {
            base.PrepareForSegue(segue, sender);
            return;


        }
	}
}
